sudo: required

language: node_js
services:
  - docker

script:
  - sudo docker-compose -f docker-compose.test.yml up -d
  - sudo docker-compose -f docker-compose.test.yml run api /bin/sh -c "./wait-for.sh db:5432 -- npm run test"
