sudo: required

language: node_js
services:
  - docker

script:
  - docker-compose -f docker-compose.test.yml up -d
  - sudo docker-compose run api /bin/sh -c "./wait-for.sh db:5432"
  - sudo docker-compose run api /bin/sh -c "npm run test"
