version: '2'

services:
  api:
    build: 
      context: .
      dockerfile: .docker/prod/Dockerfile
    depends_on: 
      - db
    ports:
      - "3000:3000"
    restart: always
    links:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'supersecret'
      NODE_ENV: 'docker'
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
       POSTGRES_PASSWORD: 'supersecret'
       POSTGRES_USER: 'postgres'
       POSTGRES_DB: 'skilled_acolyte_db'

volumes:
  db_data: