version: '2'

services:
  api:
    build: 
      context: .
      dockerfile: .docker/prod/Dockerfile
    depends_on: 
      - db
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - node_modules:/usr/src/app/node_modules
    links:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: 'postgres'
      DB_PASSWORD: PUT_SUPER_SECRET_DB_PASSWORD_HERE
      NODE_ENV: 'docker'
      POSTMARK_CLIENT_KEY: PUT_POSTMARK_CLIENT_KEY_HERE
      EVENTBRITE_TOKEN: PUT_EVENTBRITE_TOKEN_HERE
      JWT_KEY: PUT_JWT_SECRET_KEY_HERE
  db:
    image: postgres:10.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
       POSTGRES_PASSWORD: PUT_SUPER_SECRET_DB_PASSWORD_HERE
       POSTGRES_USER: 'postgres'
       POSTGRES_DB: 'skilled_acolyte_db'

volumes:
  db_data:
