default:
  host: localhost
  port: '3000'
  version: 1.0.0
  url_version: '1'

  eventbrite_token: "#{process.env.EVENTBRITE_TOKEN}"
  postmark_client_key: "#{process.env.POSTMARK_CLIENT_KEY}"
  jwt_key: this-is-secret

  slack_webhook_url: ''
  postmark_template: 6247221
  from_email: bot@unihack.net
  frontend_url: http://localhost:3000
  admin_email: admin@unihack

dev:
  host: 0.0.0.0

docker: &docker
  host: 0.0.0.0
  jwt_key: "#{process.env.JWT_KEY}"
  from_email: "#{process.env.FROM_EMAIL}"
  frontend_url: "#{process.env.FRONTEND_URL}"
  slack_webhook_url: "#{process.env.SLACK_WEBHOOK_URL}"

test:
  <<: *docker
